"""
An example for users connecting to the Sybl service and waiting for data.
"""

import pandas as pd  # type: ignore

from sybl.client import Sybl

sybl = Sybl()


def callback(train: pd.DataFrame, _predict: pd.DataFrame):
    """
    An example callback that runs with data provided by the service.

    Args:
        train: The data for the model to learn from
        _predict: The data to make predictions based on

    Returns: Predictions generated by the model
    """
    return train


sybl.register_callback(callback)
sybl.load_model("test1@test.com", "Test")

sybl.connect()
