"""
An example for users connecting to the Sybl service and waiting for data.
"""

import pandas as pd  # type: ignore
from sklearn.neighbors import KNeighborsClassifier  # type: ignore
from sklearn.linear_model import LinearRegression  # type: ignore

from sybl.client import Sybl
from sybl.client import JobConfig

sybl = Sybl()


def callback(train, predict, job_config):
    """
    An example callback that runs with data provided by the service.

    Args:
        train: The data for the model to learn from
        predict: The data to make predictions based on
        job_config: Details about the job

    Returns: Predictions generated by the model
    """
    print(job_config)
    prediction_col = job_config["prediction_column"]
    prediction_type = job_config["prediction_type"]

    y = train[prediction_col]
    X = train.drop(prediction_col, axis=1)
    predict = predict.drop(prediction_col, axis=1)

    print(prediction_type)
    if prediction_type == "classification":
        neigh = KNeighborsClassifier(n_neighbors=3)
        neigh.fit(X, y)
        return_frame = neigh.predict(predict)
    else:
        reg = LinearRegression().fit(X, y)
        return_frame = reg.predict(predict)

    return pd.DataFrame({prediction_col: return_frame})


sybl.register_callback(callback)
sybl.load_model("test1@test.com", "Test")

sybl.connect()
