"""
An example for users connecting to the Sybl service and waiting for data.
"""

import pandas as pd  # type: ignore

from sybl.client import Sybl
from sybl.client import JobConfig

sybl = Sybl()


def callback(_train: pd.DataFrame, predict: pd.DataFrame):
    """
    An example callback that runs with data provided by the service.

    Args:
        _train: The data for the model to learn from
        predict: The data to make predictions based on

    Returns: Predictions generated by the model
    """
    return pd.DataFrame(predict[predict.columns[-1]])


sybl.register_callback(callback)
sybl.load_model("test1@test.com", "Test")

sybl.connect()
