name: Continuous integration

on: [push, pull_request]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ['3.6', '3.7', '3.8', '3.9']
        name: Pytest ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python version
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Update pip
              run: python -m pip install --upgrade pip setuptools wheel
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Run pytest
              run: pytest --verbose
    lint:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ['3.6', '3.7', '3.8', '3.9']
        name: Pylint ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python version
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Update Pip
              run: python -m pip install --upgrade pip setuptools wheel
            - name: Install dependencies
              run: pip install -r requirements.txt
            - id: changed_files
              uses: jitterbit/get-changed-files@v1
            - run:
                for f in ${{ steps.changed_files.outputs.all }}; do pylint --fail-under 8 ${f}; done
